### ISSUE TITLE
Serialize puffinn.Index in Python

### ISSUE THREAD

**Issue by VarIr** [puffinn/puffinn#1]
I created a scikit-learn wrapper for puffinn, but it fails tests of `sklearn.utils.estimator_checks.check_estimator`:

``` Python3
TypeError: can't pickle puffinn.Index objects
```
Is there currently any way to serialize a built `Index`? Or are there any plans to support this in the future? This would be really cool, especially with regard to the `KNeighborsTransformers` to be introduced in scikit-learn 0.22, which will allow for simple integration of ANN libraries into pipelines. (See [example wrappers for nmslib and annoy](https://github.com/scikit-learn/scikit-learn/blob/c921aa0e73bc004cf518d43269092ea60287b8a4/examples/neighbors/approximate_nearest_neighbors.py). )

**Comment by maumueller** [comment]
Thanks for this issue! Our current pybind11 wrapper doesn't include support for pickling, but from the pybind documentation [1] this seems to be possible. @mvesterli Do you want to give it a try?

[1] https://pybind11-rtdtest.readthedocs.io/en/stable/advanced.html#pickling-support

**Comment by mvesterli** [comment]
I've added support for serialization using pickle.
Using the recommended approach in the pybind docs seems like it would use 2-3x the amount of memory of the index (first copying it into a different structure, and then moving it to python), which I'd rather avoid. The alternative is to use the `reduce` method in pickle directly which should allow serializing smaller chunks at a time. This seems to work as expected, but let me know if there are any issues with it.

**Comment by VarIr** [comment]
Awesome! Thanks a lot for that effort, wouldn't have expected this required >1000 lines...

**Comment by VarIr** [comment]
One more question: Is it possible to retrieve the vectors from the index after is was built? Or to search for neighbors just within the indexed vectors (say, by id, similar to `annoy.AnnoyIndex(...).get_nns_by_item(0, 1000)`)?
Otherwise, I'll have to keep an additional copy of the data around.

**Comment by mvesterli** [comment]
Not currently, but that should be simple to do. I'll likely add it within the next couple days.

**Comment by mvesterli** [comment]
I have added these methods as `get` and `search_from_index`. Note that the vectors are stored in a different format internally, so the retrieved vectors are normalized and may contain rounding errors compared to the originally inserted vectors.
