### ISSUE TITLE
It's slooooow to rebuild

### ISSUE THREAD

**Issue by kakusikun** [puffinn/puffinn#5]
Using Python3.6, Linux 16.04

After creating and inserting data of size [10000 x 512] to the Index, 
run `index.rebuild()`.
This line took much time, Is there any method to accelerate this part?

**Comment by maumueller** [comment]
What space parameter are you using? PUFFINN will build as many repetitions as it's allowed to do within the space requirement, which might mean a lot for such a tiny dataset. (And that will take a considerable amount of time.)

**Comment by kakusikun** [comment]
Thanks for quick reply.

`index = puffinn.Index('angular', 512, 4*1024**3)`
This is the way to create index.
Is there other way to create the index? I follow the [instruction of the README.md](https://github.com/puffinn/puffinn#python)

**Comment by maumueller** [comment]
I see. With this space requirement, you'll end up using around 40k repetitions (because the dataset is so tiny). 

Please try out `index = puffinn.Index('angular', 512, 50*1024**2)` which is somehow more realistic. 

@mvesterli: Maybe we could safeguard against such parameter choices?

**Comment by kakusikun** [comment]
It's faster when using lower value of memory limit. 
Thanks for your advice.
