### ISSUE TITLE
Error running test.py

### ISSUE THREAD

**Issue by thomasahle** [puffinn/puffinn#9]
I'm getting this:

    $ py test.py
    Traceback (most recent call last):
      File "test.py", line 11, in <module>
        index.insert(v)
    TypeError: insert(): incompatible function arguments. The following argument types are supported:
        1. (self: puffinn.Index, arg0: list) -> None
    
    Invoked with: <puffinn.Index object at 0x103f544f0>, array([-0.78503973, -0.33426136, -1.10496011,  0.36873416, -0.42192833,

Changing `index.insert(v)` to `index.insert(v.tolist())` and `index.search(query, 10, 0.8)` to `index.search(query.tolist(), 10, 0.8)` fixes the problem.

**Comment by maumueller** [comment]
Thanks @thomasahle.

I couldn't find `test.py` in the repo, is this a file that you created? And yes, it doesn't accept a numpy array at the moment as an argument. Was there any particular reason for this, @mvesterli ? (It's the same in ann-benchmarks at https://github.com/erikbern/ann-benchmarks/blob/master/ann_benchmarks/algorithms/puffinn.py which looks a bit inefficient.)

**Comment by thomasahle** [comment]
Sorry, my bad. I think it's based on the example on the github page, but that doesn't use numpy arrays either, so I've just confused myself.
